config/routes.rb
Rails.application.routes.draw do

  match '/contact', to: 'welcome#contact', via: 'get'
  match '/about', to: 'welcome#about', via: 'get'

  resources :users, only: [:new, :show, :create]
  match '/signup', to: 'users#new', via: 'get'
  match '/export', to: 'users#export', via: 'get'
  match '/api/user/study_new_word', to: 'users#api_study_new_word', via: 'post'
  match '/api/user/study_card', to: 'users#api_study_card', via: 'post'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  resources :words, only: [:new, :show]
  match '/search', to: 'words#search', via: 'get'
  match '/update_content', to: 'words#update_content', via: 'get'
  match '/api/words/get', to: 'words#api_get', via: 'get'
  
  resources :new_words, only: [:new, :index]
  match '/new_words/play', to: 'new_words#play', via: 'get'
  match '/new_words/delete', to: 'new_words#delete', via: 'delete'
  match '/api/new_words/add', to: 'new_words#api_add', via: 'post'
  match '/api/new_words/delete', to: 'new_words#api_delete', via: 'delete'
  
  resources :cards, only: [:index]
  match '/cards/play', to: 'cards#play', via: 'get'
  match '/api/cards/batch', to: 'cards#api_get_batch', via: 'get'
  match '/api/cards/get', to: 'cards#api_get', via: 'get'
  match '/api/cards/add', to: 'cards#api_add_word', via: 'post'
  match '/api/cards/schedule', to: 'cards#api_new_schedule', via: 'post'
  match '/api/cards/delete', to: 'cards#api_delete', via: 'delete'

  root 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @user = current_user
  end

  def about
  end

  def contact
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def today_cards_count
        @user.cards.where(["schedule < ?", DateTime.tomorrow.beginning_of_day]).count
    end
    
    def total_cards_count
        @user.cards.count
    end
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.haml
%h1 Welcome#contact
%p Find me in app/views/welcome/contact.html.erb

app/views/welcome/home.html.haml
.jumbotron
  %h1 Hello!
  %p Welcome to #mituba's English word learning place.
    
  - if signed_in?
    %div.row
      %div.col-lg-4
        - _options = { class: "btn btn-default btn-block", style: "text-align: left" }
        = link_to new_words_play_path, _options do
          %span PLAY NEW WORDS
          %span.badge.pull-right= @user.study_new_word_count
        = link_to cards_play_path, _options do
          %span PLAY CARDS
          %span.badge.pull-right= @user.study_card_count
        = link_to "ADD NEW WORDS", new_new_word_path, _options
        = link_to new_words_path, _options do
          %span LIST NEW WORDS
          %span.badge.pull-right= @user.new_words.count
        = link_to cards_path, _options do
          %span LIST CARDS
          %span.badge.pull-right= "#{today_cards_count}/#{total_cards_count}"
        = link_to "EXPORT", export_path, _options
  - else
    %div(style="text-align:right")
      = link_to "Sign Up", signup_path, class:"btn btn-lg btn-primary", style:"width:120px"
      = link_to "Sign In", signin_path, class:"btn btn-lg btn-primary", style:"width:120px"

.row
  .col-xs-12
    %h2 Other Links
    .list-group
      %p= link_to "About", about_path, class:"list-group-item"
      %p= link_to "Contact", contact_path, class:"list-group-item"