config/routes.rb
Rails.application.routes.draw do

  match '/contact', to: 'welcome#contact', via: 'get'
  match '/about', to: 'welcome#about', via: 'get'

  resources :users, only: [:new, :show, :create]
  match '/signup', to: 'users#new', via: 'get'
  match '/export', to: 'users#export', via: 'get'
  match '/api/user/study_new_word', to: 'users#api_study_new_word', via: 'post'
  match '/api/user/study_card', to: 'users#api_study_card', via: 'post'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  resources :words, only: [:new, :show]
  match '/search', to: 'words#search', via: 'get'
  match '/update_content', to: 'words#update_content', via: 'get'
  match '/api/words/get', to: 'words#api_get', via: 'get'
  
  resources :new_words, only: [:new, :index]
  match '/new_words/play', to: 'new_words#play', via: 'get'
  match '/new_words/delete', to: 'new_words#delete', via: 'delete'
  match '/api/new_words/add', to: 'new_words#api_add', via: 'post'
  match '/api/new_words/delete', to: 'new_words#api_delete', via: 'delete'
  
  resources :cards, only: [:index]
  match '/cards/play', to: 'cards#play', via: 'get'
  match '/api/cards/batch', to: 'cards#api_get_batch', via: 'get'
  match '/api/cards/get', to: 'cards#api_get', via: 'get'
  match '/api/cards/add', to: 'cards#api_add_word', via: 'post'
  match '/api/cards/schedule', to: 'cards#api_new_schedule', via: 'post'
  match '/api/cards/delete', to: 'cards#api_delete', via: 'delete'

  root 'welcome#home'

end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
		      <%= link_to "WORD HALO", root_path, id: "logo", class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <form class="navbar-form navbar-left" role="form" action="/search" method="get">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Enter an English word">
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default">Search</button>
              </span>
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
      			<% if signed_in? %>
      			<li><%= link_to current_user.name.upcase, current_user %></li>
      			<li class="visible-xs-block">
      			  <%= link_to new_words_play_path do %>
                <strong>PLAY NEW WORDS</strong>
                <span class="badge pull-right"><%= current_user.study_new_word_count %></span>
              <% end %>
            </li>
       			<li class="visible-xs-block">
      			  <%= link_to cards_play_path do %>
                <strong>PLAY CARDS</strong>
                <span class="badge pull-right"><%= current_user.study_card_count %></span>
              <% end %>
       			</li>
            <li class="visible-xs-block">
              <%= link_to new_new_word_path do %>
                <strong>ADD NEW WORDS</strong>
              <% end %>
            </li>
      			<li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
      			<% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
      			<li><%= link_to "Sign In", signin_path %></li>
      			<% end %>
            <li><%= link_to "CSS Help", 'http://getbootstrap.com/components' %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Wordhalo</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container" style="padding-top: 70px">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
	    <%= yield %>
        <%= render 'layouts/footer' %>
        <p style="padding-top: 40px"></p>
        <%= debug(params) if Rails.env.development? %>
	</div>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :javascript %>
</html>